"""Добавлено поле для текстуры

Revision ID: 01390416d978
Revises: dbdd29f802a3
Create Date: 2025-09-25 13:28:50.089372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01390416d978'
down_revision = 'dbdd29f802a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texture_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('texture_url')

    # ### end Alembic commands ###
