"""Добавлены поля composition и certificates

Revision ID: 51587bb57372
Revises: 336b65dd2a36
Create Date: 2025-09-27 23:31:28.677636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51587bb57372'
down_revision = '336b65dd2a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composition', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certificates', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('certificates')
        batch_op.drop_column('composition')

    # ### end Alembic commands ###
