"""Добавление колонок old_price и is_best_seller

Revision ID: 9a427562960e
Revises: 
Create Date: 2025-09-25 10:08:51.086763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a427562960e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_best_seller', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_best_seller')
        batch_op.drop_column('image_url')
        batch_op.drop_column('old_price')

    # ### end Alembic commands ###
